name: automatic_challan_generator
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"  # Ensure the correct Dart SDK version

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  camera: ^0.11.1
  url_launcher:
  intl: ^0.18.1
  csv: ^5.0.2
  uuid: ^3.0.6
  path_provider: ^2.1.5
  firebase_core: ^2.32.0  # Compatible with firebase_auth
  firebase_auth: ^4.20.0  # Use latest stable version
  firebase_storage:
  cloud_firestore: ^4.15.0
  firebase_database: ^10.4.0
  printing: ^5.11.0
  http: ^0.13.6
  permission_handler: ^11.3.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  google_maps_flutter: ^2.5.0
  intl: ^0.18.1


  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/Logo1.png
    - assets/Logo1r.png
    - assets/challan_data.csv
